- name: Setting up vim plugin manager
  ansible.builtin.command: curl -fLo /home/dang/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  become_user: dang

- name: Making vim directory structure
  file:
    path: /home/dang/.vim/{{item}}
    state: directory
    mode: '0755'
  with_items:
    ['colors','after','after/syntax','after/ftplugin','.vimwiki']
  become_user: dang

- name: Adding vim colorschemes
  copy:
    src: files/{{item}}
    dest: /home/dang/.vim/colors
    owner: dang
    group: dang
    mode: 0640
  with_items:
    ['solarized.vim','seoul256.vim','seoul256-light.vim']
  become_user: dang

- name: Adding vim C syntax
  copy:
    src: files/c.vim
    dest: /home/dang/.vim/after/syntax/c.vim
    owner: dang
    group: dang
    mode: 0640
  become_user: dang

- name: Adding vim VimWiki syntax
  copy:
    src: files/vimwiki.vim
    dest: /home/dang/.vim/after/ftplugin/vimwiki.vim
    owner: dang
    group: dang
    mode: 0640
  become_user: dang

- name: Setting vimrc
  copy:
    src: files/vimrc
    dest: /home/dang/.vimrc 
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Making xmonad directory
  ansible.builtin.file:
    path: /home/dang/.xmonad
    state: directory
    mode: '0755'
  become_user: dang

- name: Making config directory
  ansible.builtin.file:
    path: /home/dang/.config
    state: directory
    mode: '0755'
  become_user: dang

- name: Making xmobar directory
  ansible.builtin.file:
    path: /home/dang/.config/xmobar
    state: directory
    mode: '0755'
  become_user: dang

- name: Setting xmonad config
  copy:
    src: files/xmonad
    dest: /home/dang/.xmonad/config.hs
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Setting xmonadctl source
  copy:
    src: files/xmonadctl
    dest: /home/dang/.xmonad/xmonadctl.hs
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Copying Cabal build script
  copy:
    src: /usr/local/share/examples/xmonad/build
    dest: /home/dang/.xmonad/build
    owner: dang
    group: dang
    mode: 0555
  become_user: dang

- name: Copying Cabal xmonad config 
  copy:
    src: /usr/local/share/examples/xmonad/xmonad-config.cabal
    dest: /home/dang/.xmonad/xmonad-config.cabal
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Change build-depends to include containers
  lineinfile:
    path: /home/dang/.xmonad/xmonad-config.cabal
    regexp: 'build-depends'
    line: '  build-depends: base, xmonad, xmonad-contrib, containers'
  become_user: dang

- name: Setting shrc
  copy:
    src: files/shrc
    dest: /home/dang/.shrc
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Setting gitconfig
  copy:
    src: files/gitconfig
    dest: /home/dang/.gitconfig
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Setting picom
  copy:
    src: files/picom
    dest: /home/dang/.config/picom.conf
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Setting xinitrc
  copy:
    src: files/xinitrc
    dest: /home/dang/.xinitrc
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Setting Xresources
  copy:
    src: files/xresources
    dest: /home/dang/.Xresources
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Setting X11 nvidia-driver file
  copy:
    src: files/driver-nvidia.conf
    dest: /usr/local/etc/X11/xorg.conf.d/driver-nvidia.conf
    owner: root
    group: wheel
    mode: 0440

- name: Adding user scripts
  copy:
    src: scripts
    dest: /home/dang/.local/bin
  become_user: dang
