- name: Setting up vim plugin manager
  ansible.builtin.command: curl -fLo /home/dang/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  become_user: dang

- name: Making vim directory structure
  ansible.builtin.file:
    path: /home/dang/.vim/{{item}}
    state: directory
    mode: '0755'
  with_items:
    ['colors','after','after/syntax','after/ftplugin']
  become_user: dang

# - name: Making vim colors directory
#   ansible.builtin.file:
#     path: /home/dang/.vim/colors
#     state: directory
#     mode: '0755'
#   become_user: dang

# - name: Making vim after directory
#   ansible.builtin.file:
#     path: /home/dang/.vim/after
#     state: directory
#     mode: '0755'
#   become_user: dang

# - name: Making vim after/syntax directory
#   ansible.builtin.file:
#     path: /home/dang/.vim/after/syntax
#     state: directory
#     mode: '0755'
#   become_user: dang

# - name: Making vim after/ftplugin directory
#   ansible.builtin.file:
#     path: /home/dang/.vim/after/ftplugin
#     state: directory
#     mode: '0755'
#   become_user: dang

- name: Adding vim colorschemes
  copy:
    src: files/{{item}}
    dest: /home/dang/.vim/colors
    owner: dang
    group: dang
    mode: 0640
  with_items:
    ['solarized.vim','seoul256.vim','seoul256-light.vim']
  become_user: dang

- name: Adding vim C syntax
  copy:
    src: files/c.vim
    dest: /home/dang/.vim/after/syntax/c.vim
    owner: dang
    group: dang
    mode: 0640
  become_user: dang

- name: Adding vim VimWiki syntax
  copy:
    src: files/vimwiki.vim
    dest: /home/dang/.vim/after/ftplugin/vimwiki.vim
    owner: dang
    group: dang
    mode: 0640
  become_user: dang

- name: Setting vimrc
  copy:
    src: files/vimrc
    dest: /home/dang/.vimrc 
    owner: dang
    group: dang
    mode: 0644
  become_user: dang

- name: Setting picom
  copy:
    src: files/picom
    dest: /home/dang/.config/picom.conf
    owner: dang
    group: dang
    mode: 0644
  become_user: dang
