# - name: Making ~/.vim directory
#   ansible.builtin.file:
#     path: /home/dang/.vim
#     state: directory
#     mode: '0755'

# - name: Making ~/.vim/autoload directory (plugin manager)
#   ansible.builtin.file:
#     path: /home/dang/.vim/autoload
#     state: directory
#     mode: '0755'
- name: Setting up vim plugin manager
  ansible.builtin.command: curl -fLo /home/dang/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Setting vimrc
  copy:
    src: files/vimrc
    dest: /home/dang/.vimrc 
    owner: dang
    group: dang
    mode: 0644
