- name: Making ~/.vim directory
  ansible.builtin.file:
    path: /home/dang/.vim
    state: directory
    mode: '0755'

- name: Setting vimrc
  copy:
    src: files/vimrc
    dest: /home/dang/.vimrc 
    owner: dang
    group: dang
    mode: 0644
