- name: Create Ansible User
  user:
    name: ansible
    system: yes

- name: Copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /usr/local/etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
